#!/bin/bash
# Converts fountain to html and uploads it on the website
cd /home/victor/Documents/Githeatre/navicellateatro.github.io && /home/victor/Documents/Githeatre/Textplay/textplay < scriptedlives.fountain > index.html && git add . && git commit -m "updated screenplay" && git push
